[project]
name = "portfolios-optimization"
version = "0.1.0"
description = ""
authors = [
    {name = "Igor Astashov",email = "igora@development.ru"}
]
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [
    "scipy (==1.14.1)",
    "statsmodels (==0.14.4)",
    "sktime (==0.36.0)",
    "tqdm (>=4.67.1,<5.0.0)",
    "requests (==2.31.0)",
    "python-binance (==1.0.28)",
    "matplotlib (==3.10.0)",
    "plotly (==5.14.1)",
    "nbformat (==5.10.4)",
    "jinja2 (==3.1.4)",
    "seaborn (==0.13.2)",
    "finrl @ git+https://github.com/AI4Finance-Foundation/FinRL.git",
    "pandas-market-calendars (>=5.0.0,<6.0.0)",
    "streamlit (>=1.44.1,<2.0.0)",
   "ta (==0.10.2)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
